### ISSUE TITLE
What is about the param (block_per_split)

### ISSUE THREAD

**Issue by fann1993814** [ksw0306/FloWaveNet#19]
I haven't seen the parameter in previous version.
Can anyone explain the effect of the parameter (block_per_split)?
The auther proposed the new version for Multi-scale architecture in 1 Feb.
I am so curious about the new feature.

Because I already trained the model at previous version.
I hesitate whether I need retrain the model.
(Training time is so long...)

**Comment by L0SG** [comment]
`--block_per_split` is an integration of the multi-scale architecture from [Real NVP](https://arxiv.org/abs/1605.08803) and we use it as the default architecture since it improves the performance. We're afraid the previous model would not be compatible. We'll upload the updated version of the arXiv paper for detailed explanations of the master branch model soon!
